#Word Embedding Techniques using Embedding Layer in Keras


In [2]:
from tensorflow.keras.preprocessing.text import one_hot


In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
voc_size=10000


In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[4456, 7577, 7610, 6849], [4456, 7577, 7610, 3962], [4456, 2546, 7610, 6200], [7975, 1996, 5666, 1301, 3269], [7975, 1996, 5666, 1301, 2140], [4914, 4456, 976, 7610, 3245], [6692, 6889, 8916, 1301]]


In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4456 7577 7610 6849]
 [   0    0    0    0 4456 7577 7610 3962]
 [   0    0    0    0 4456 2546 7610 6200]
 [   0    0    0 7975 1996 5666 1301 3269]
 [   0    0    0 7975 1996 5666 1301 2140]
 [   0    0    0 4914 4456  976 7610 3245]
 [   0    0    0    0 6692 6889 8916 1301]]


In [12]:
dim=10


In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
print(model.predict(embedded_docs))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 251ms/step
[[[ 2.0098533e-02 -1.2025990e-02  5.0513260e-03 -2.0989824e-02
   -2.0671487e-02 -8.3080418e-03 -2.5422685e-03  4.6797704e-02
    3.1150509e-02  1.7765690e-02]
  [ 2.0098533e-02 -1.2025990e-02  5.0513260e-03 -2.0989824e-02
   -2.0671487e-02 -8.3080418e-03 -2.5422685e-03  4.6797704e-02
    3.1150509e-02  1.7765690e-02]
  [ 2.0098533e-02 -1.2025990e-02  5.0513260e-03 -2.0989824e-02
   -2.0671487e-02 -8.3080418e-03 -2.5422685e-03  4.6797704e-02
    3.1150509e-02  1.7765690e-02]
  [ 2.0098533e-02 -1.2025990e-02  5.0513260e-03 -2.0989824e-02
   -2.0671487e-02 -8.3080418e-03 -2.5422685e-03  4.6797704e-02
    3.1150509e-02  1.7765690e-02]
  [-8.2486272e-03 -1.5920363e-02 -2.8666331e-02  3.0649789e-03
   -1.4477182e-02 -2.9018426e-02  4.8408832e-02  2.5611009e-02
    7.8331456e-03  1.3265226e-02]
  [ 1.7276417e-02 -1.9767797e-02 -2.3990095e-02 -2.7146637e-02
    3.2378640e-02  2.7233649e-02 -2.8247584e-02  1.9442663e-03
    1.3028983e-02  4.9288049e-03]
 

In [17]:
embedded_docs[1]


array([   0,    0,    0,    0, 4456, 7577, 7610, 3962], dtype=int32)

In [18]:
print(model.predict(embedded_docs)[1])


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[[ 0.02009853 -0.01202599  0.00505133 -0.02098982 -0.02067149 -0.00830804
  -0.00254227  0.0467977   0.03115051  0.01776569]
 [ 0.02009853 -0.01202599  0.00505133 -0.02098982 -0.02067149 -0.00830804
  -0.00254227  0.0467977   0.03115051  0.01776569]
 [ 0.02009853 -0.01202599  0.00505133 -0.02098982 -0.02067149 -0.00830804
  -0.00254227  0.0467977   0.03115051  0.01776569]
 [ 0.02009853 -0.01202599  0.00505133 -0.02098982 -0.02067149 -0.00830804
  -0.00254227  0.0467977   0.03115051  0.01776569]
 [-0.00824863 -0.01592036 -0.02866633  0.00306498 -0.01447718 -0.02901843
   0.04840883  0.02561101  0.00783315  0.01326523]
 [ 0.01727642 -0.0197678  -0.02399009 -0.02714664  0.03237864  0.02723365
  -0.02824758  0.00194427  0.01302898  0.0049288 ]
 [-0.01444751 -0.02674842 -0.04422563 -0.01137204  0.02055988  0.03505156
  -0.02024489 -0.01163904  0.00837784  0.01829636]
 [ 0.01403269 -0.02957746  0.04373027  0.04955767 -0.03303297 -0.02603408
  -0.00502217